using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AgentEcosystem.Agents.Core;
using AgentEcosystem.McpTools;
using Microsoft.Extensions.Logging;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.ChatCompletion;

namespace AgentEcosystem.Agents;

/// <summary>
/// Analysis Agent — GPT-powered data analysis agent.
/// 
/// .NET adaptation of ADK's LlmAgent concept:
/// - Reads data from the Researcher Agent (via State)
/// - Analyzes, summarizes, and structures the data with GPT
/// - Saves results using MCP tools (FileSystem, Database)
/// - Presents the final result to the user
/// 
/// This Agent in the A2A Flow:
/// - Receives data as an A2A task from the Researcher Agent
/// - Returns the analysis result as an A2A artifact
/// - Saves to file and database via MCP
/// </summary>
public class AnalysisAgent : BaseAgent
{
    private readonly Kernel _kernel;
    private readonly McpFileSystemTools _fileSystemTools;
    private readonly McpDatabaseTools _databaseTools;
    private readonly ILogger<AnalysisAgent> _logger;

    public AnalysisAgent(
        Kernel kernel,
        McpFileSystemTools fileSystemTools,
        McpDatabaseTools databaseTools,
        ILogger<AnalysisAgent> logger)
    {
        _kernel = kernel;
        _fileSystemTools = fileSystemTools;
        _databaseTools = databaseTools;
        _logger = logger;

        Name = "AnalysisAgent";
        Description = "An analysis agent that analyzes research data and produces structured results.";
    }

    /// <summary>
    /// Executes the analysis task.
    /// Reads the research report from State, analyzes it, and saves the results.
    /// </summary>
    public override async Task<AgentEvent> RunAsync(
        AgentContext context,
        CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("[AnalysisAgent] Analysis starting...");

        try
        {
            // === STEP 1: Read Data from State (ADK Pattern) ===
            // Read the data written to state by the Researcher Agent
            var query = context.GetState<string>("research_query") ?? context.UserQuery;
            var searchResults = context.GetState<string>("search_results") ?? "";
            var researchReport = context.GetState<string>("research_report") ?? "";

            if (string.IsNullOrEmpty(researchReport))
            {
                return new AgentEvent
                {
                    Author = Name,
                    Status = "failed",
                    Content = "No research data found for analysis. " +
                              "The Researcher Agent must be run first."
                };
            }

            // === STEP 2: Analyze with GPT ===
            var systemPrompt = """
                You are an expert analysis agent. Your task is to:
                1. Perform an in-depth analysis of the research report
                2. Identify main themes and patterns
                3. Organize the information in a logical structure
                4. Create a professional Markdown report
                
                Report Format:
                # [Topic Title]
                
                ## Executive Summary
                [Brief and concise key findings]
                
                ## Detailed Analysis
                ### [Sub-heading 1]
                [Detailed analysis]
                
                ### [Sub-heading 2]
                [Detailed analysis]
                
                ## Sources and References
                [Source list]
                
                ## Conclusion and Recommendations
                [Overall assessment and recommendations]
                
                ---
                *This report was automatically generated by the AI Agent Ecosystem.*
                *Created through the Researcher Agent → Analysis Agent pipeline.*
                
                Respond in English. Use an academic, professional, and clear tone.
                """;

            var userMessage = $"""
                Research Topic: {query}
                
                Research Report:
                {researchReport}
                
                Raw Search Results:
                {searchResults}
                
                Analyze this data and prepare a structured report in the format above.
                """;

            _logger.LogInformation("[AnalysisAgent] Generating analysis report with Semantic Kernel...");

            var chatService = _kernel.GetRequiredService<IChatCompletionService>();
            var history = new ChatHistory();
            history.AddSystemMessage(systemPrompt);
            history.AddUserMessage(userMessage);

            var result = await chatService.GetChatMessageContentsAsync(
                history,
                cancellationToken: cancellationToken);

            var analysisResult = result.LastOrDefault()?.Content ?? "Failed to generate analysis report.";

            _logger.LogInformation(
                "[AnalysisAgent] Analysis report prepared ({Length} characters)",
                analysisResult.Length);

            // === STEP 3: Save with MCP Tools ===
            // The MCP protocol enables agents to access external resources (file, DB)

            // 3a. Save to file (MCP:FileSystem)
            var fileName = $"{SanitizeForFileName(query)}-{DateTime.UtcNow:yyyyMMdd-HHmmss}.md";
            var fileSaveResult = await _fileSystemTools.SaveResearchToFileAsync(fileName, analysisResult);
            _logger.LogInformation("[AnalysisAgent] MCP:FileSystem result: {Result}", fileSaveResult);

            // 3b. Save to database (MCP:Database)
            var dbSaveResult = await _databaseTools.SaveResearchAsync(
                query, searchResults, analysisResult, "web-search");
            _logger.LogInformation("[AnalysisAgent] MCP:Database result: {Result}", dbSaveResult);

            // === STEP 4: Write to State and Return Result ===
            context.SetState("analysis_result", analysisResult);
            context.SetState("analysis_file", fileName);
            context.SetState("analysis_status", "completed");

            return new AgentEvent
            {
                Author = Name,
                Status = "completed",
                Content = analysisResult,
                Actions = new EventActions
                {
                    StateUpdates = new Dictionary<string, object>
                    {
                        ["analysis_result"] = analysisResult,
                        ["analysis_file"] = fileName
                    },
                    // Escalate = true: Pipeline completed, notify parent agent
                    Escalate = true
                }
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[AnalysisAgent] Analysis error");

            return new AgentEvent
            {
                Author = Name,
                Status = "failed",
                Content = $"An error occurred during analysis: {ex.Message}"
            };
        }
    }

    private static string SanitizeForFileName(string text)
    {
        var sanitized = text.Length > 50 ? text[..50] : text;
        foreach (var c in System.IO.Path.GetInvalidFileNameChars())
            sanitized = sanitized.Replace(c, '-');
        return sanitized.Replace(' ', '-').ToLowerInvariant();
    }
}
